name: 1.1.$(Build.BuildId)

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: bleddynrichards.Assembly-Info-Task.Assembly-Info-Task.Assembly-Info-NetFramework@2
  displayName: 'Set Assembly Manifest Data'
  inputs:
    Path: Source
    FileNames: '**\AssemblyInfo.cs'
    Title: 'SQL Compact Query Analyzer'
    Product: 'SQL Compact Query Analyzer'
    Description: 'Database management and query analyzer tool for SQL Server Compact Edition'
    Company: 'Christian Resma Helle'
    Copyright: 'Copyright © Christian Resma Helle 2010'
    VersionNumber: '$(build.buildNumber).*'
    FileVersionNumber: '$(build.buildNumber)'

- task: PowerShell@2
  displayName: 'Build'
  inputs:
    targetType: 'inline'
    script: |
      cd Source
      ./build.ps1

- task: CopyFiles@2
  inputs:
    SourceFolder: 'Source/Artifacts'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- powershell: |
   mv $(build.artifactstagingdirectory)/SQLCEQueryAnalyzer-Binaries.zip $(build.artifactstagingdirectory)/SQL.Compact.Query.Analyzer.v$(build.buildNumber).zip
   mv $(build.artifactstagingdirectory)/SQLCEQueryAnalyzer-Setup.exe $(build.artifactstagingdirectory)/SQL.Compact.Query.Analyzer.Setup.v$(build.buildNumber).exe
  displayName: 'Rename Artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'