name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 8 * * *'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cake Build
      run: ./build.ps1 -Verbosity Diagnostic
      working-directory: Source

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          Source/Artifacts/*
