name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 8 * * *'

env:
  VERSION: 1.3.${{ github.run_number }}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Update Version
      run: |
        ((Get-Content -Path Source\Editor\Properties\AssemblyInfo.cs -Raw) -Replace "1.0.*", "${{ env.VERSION }}") | Set-Content -Path Source\Editor\Properties\AssemblyInfo.cs
        ((Get-Content -Path Source\SqlCeDatabase\Properties\AssemblyInfo.cs -Raw) -Replace "1.0.*", "${{ env.VERSION }}") | Set-Content -Path Source\SqlCeDatabase\Properties\AssemblyInfo.cs
        ((Get-Content -Path Source\SqlCeDatabase31\Properties\AssemblyInfo.cs -Raw) -Replace "1.0.*", "${{ env.VERSION }}") | Set-Content -Path Source\SqlCeDatabase31\Properties\AssemblyInfo.cs
        ((Get-Content -Path Source\SqlCeDatabase35\Properties\AssemblyInfo.cs -Raw) -Replace "1.0.*", "${{ env.VERSION }}") | Set-Content -Path Source\SqlCeDatabase35\Properties\AssemblyInfo.cs
        ((Get-Content -Path Source\SqlCeDatabase40\Properties\AssemblyInfo.cs -Raw) -Replace "1.0.*", "${{ env.VERSION }}") | Set-Content -Path Source\SqlCeDatabase40\Properties\AssemblyInfo.cs

    - name: Cake Build
      run: ./build.ps1 --verbosity Diagnostic
      working-directory: Source

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          Source/Artifacts/*
