name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'release'

env:
  VERSION: 1.3.${{ github.run_number }}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Update Version
      run: |
        ((Get-Content -Path Source\Editor\Properties\AssemblyInfo.cs -Raw) -Replace "1.0.*", "${{ env.VERSION }}"")]") | Set-Content -Path Source\Editor\Properties\AssemblyInfo.cs
        ((Get-Content -Path Source\SqlCeDatabase\Properties\AssemblyInfo.cs -Raw) -Replace "1.0.*", "${{ env.VERSION }}"")]") | Set-Content -Path Source\SqlCeDatabase\Properties\AssemblyInfo.cs
        ((Get-Content -Path Source\SqlCeDatabase31\Properties\AssemblyInfo.cs -Raw) -Replace "1.0.*", "${{ env.VERSION }}"")]") | Set-Content -Path Source\SqlCeDatabase31\Properties\AssemblyInfo.cs
        ((Get-Content -Path Source\SqlCeDatabase35\Properties\AssemblyInfo.cs -Raw) -Replace "1.0.*", "${{ env.VERSION }}"")]") | Set-Content -Path Source\SqlCeDatabase35\Properties\AssemblyInfo.cs
        ((Get-Content -Path Source\SqlCeDatabase40\Properties\AssemblyInfo.cs -Raw) -Replace "1.0.*", "${{ env.VERSION }}"")]") | Set-Content -Path Source\SqlCeDatabase40\Properties\AssemblyInfo.cs
        ((Get-Content -Path Source\Setup-x86.iss -Raw) -Replace "1.0.0", "${{ env.VERSION }}") | Set-Content -Path Source\Setup-x86.iss
        ((Get-Content -Path Source\Setup-x64.iss -Raw) -Replace "1.0.0", "${{ env.VERSION }}") | Set-Content -Path Source\Setup-x64.iss

    - name: Cake Build
      run: ./build.ps1 --verbosity Diagnostic
      working-directory: Source

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Installer (x64)
        path: Source/Artifacts/SQLCEQueryAnalyzer-Setup-x64.exe

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Binaries (x64)
        path: Source/Artifacts/SQLCEQueryAnalyzer-Binaries-x64.zip

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Installer (x86)
        path: Source/Artifacts/SQLCEQueryAnalyzer-Setup-x86.exe

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Binaries (x86)
        path: Source/Artifacts/SQLCEQueryAnalyzer-Binaries-x86.zip
  
  publish:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Create tag
      uses: actions/github-script@v3
      with:
        github-token: ${{ github.token }}
        script: |
          github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ env.VERSION }}",
            sha: context.sha
          })

    - name: Create draft release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: v${{ env.VERSION }}
        draft: true
        prerelease: false

    - uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Upload Installer (x64) asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: artifacts/Installer (x64)/SQLCEQueryAnalyzer-Setup-x64.exe
        asset_name: SQLCEQueryAnalyzer-Setup-x64.exe
        asset_content_type: application/zip

    - name: Upload Binaries (x64) asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: artifacts/Binaries (x64)/SQLCEQueryAnalyzer-Binaries-x64.zip
        asset_name: SQLCEQueryAnalyzer-Binaries-x64.zip
        asset_content_type: application/zip

    - name: Upload Installer (x86) asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: artifacts/Installer (x86)/SQLCEQueryAnalyzer-Setup-x86.exe
        asset_name: SQLCEQueryAnalyzer-Setup-x86.exe
        asset_content_type: application/zip

    - name: Upload Binaries (x86) asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: artifacts/Binaries (x86)/SQLCEQueryAnalyzer-Binaries-x86.zip
        asset_name: SQLCEQueryAnalyzer-Binaries-x86.zip
        asset_content_type: application/zip
